### ISSUE TITLE
Dealing with errors when the error requires script interruption ?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sorunlib#115]
This is an interesting one. @samdayweiss and SATp3 were trying to run a scan through `run.seq.scan`. the ACU agent encountered an error and stopped scanning something like 30 seconds into the scan. The nextline+sorunlib combo wouldn't have caught the error until 80 minutes later when the scan was supposed to stop. 

In that situation the only thing to do right now is to interrupt the nextline script, but when we do that the "finally" block of seq.scan never runs. Is there a way to have that run when we interrupt things? (But also, it seems like an ACU error there would also cause the finally block to throw an error before turning off smurf streams?)

**Comment by TaiSakuma** [comment]
That is odd. In Nextline, the `finally` block is supposed to run if the `try` block is `interrupted.`

**Comment by BrianJKoopman** [comment]
Is this from run 57? If yes, it looks like the `finally` block did run, but as you said it ran into an ACU error and didn't stop the SMuRF streams (like in #95.)

**Comment by BrianJKoopman** [comment]
So I'm working on a solution for this, but my implementation only works for the ACU at the moment (or well, any *single* process), since it's essentially a replacement for this line:
https://github.com/simonsobs/sorunlib/blob/bfa059c38719c57ce1b7e7dd0b6c37df760b123b/src/sorunlib/seq.py#L46-L47

Instead, I would have a loop that just repeatedly checks `acu.generate_scan.status()` until `stop_time` and raise an exception if the scan crashes.

This doesn't work for the SMuRFs though, if the streams fail for some reason mid-scan we won't notice until the end of the scan when they are turned off (and presumably return a 'FAILED' then.)

Is that a common/anticipated failure mode? I'll have to think about how we should implement that...
